### ISSUE TITLE
wrong attachment name

### ISSUE THREAD

**Issue by oligalma** [joomlaworks/k2#213]
Hi,
I attached some file types (png, rtf, pdf) to a K2 item and they are stored well. However:
I attached a css file called "main.css" to a K2 item but it is stored as "main.css.txt" instead of "main.css". 
I attached a php file called "main.php" to a K2 item but it is stored as "main.php.txt" instead of "main.php". 

thanks for your attention
Marc

**Comment by kavadas** [comment]
@oligalma 

It's your server that fails to detect the correct mime type of the file in all possible ways. Then the class we are using is taking the last option which is what the browser says. You have to either update your server's PHP version and setup or try to use a different browser. As @K2Joom correctly wrote the issue is discussed in detail in #54 .
