### ISSUE TITLE
 k2 does not provide an event on deletion.

### ISSUE THREAD

**Issue by iStampa** [joomlaworks/k2#242]
I plan on using j2store with k2 and was wandering if the issue with k2 plugin (deletion of items) can be solved.

From j2store "k2 does not provide an event on deletion. So that limitation is still there."

**Comment by iStampa** [comment]
I was hoping someone can give me an idea on whether this is something you are considering to look at in the near future. Thanks.

**Comment by kavadas** [comment]
There are several ways to know when a K2 item is deleted:

1. Listen to the "onFinderAfterDelete" event.
2. Create a system plugin and check the task variable.
3. Use the JObserver interface.

Since there are already ways to listen to the delete event, i don't think we are going to add any extra event in K2v2.
