### ISSUE TITLE
K2 Dev Build - Close button not working on add new item modal box from K2 User

### ISSUE THREAD

**Issue by KannanNaidu** [joomlaworks/k2#263]
When you click Add new item from K2 User module, the modal box does not close when clicking the close button or the X button. 

It works when you save and add the article. Before clicking save, the close button does not work.

**Comment by kricore** [comment]
Hello Kannan,

Does this happen with 2.6.9 or the DEV version?

**Comment by KannanNaidu** [comment]
Hello Kricore.

The DEV version 2.7.0

**Comment by kavadas** [comment]
@KannanNaidu 

Hi. Can you please grab a fresh copy from http://getk2.org/assets/get/ and try again? Remember to clean your browser cache first.

**Comment by KannanNaidu** [comment]
@kavadas 

Its still the same. Cleared browser cache, did the install and nothing changed. I still can't close the modal box. 
![component_k2](https://cloud.githubusercontent.com/assets/1253496/12324528/1323e5c0-bafe-11e5-86db-bf7854c9c7e3.png)

**Comment by K2Joom** [comment]
Check for JS conflicts.


Regards,

Simon Wells
K2Joom
Bespoke Website Developments - Joomla Specialist
Domain Names - Sites - Hosting - SEO - Training

**Comment by kricore** [comment]
We are considering on changing the modal to something more lightweight and less intrusive (think Bootstrap 2 conflicts).

**Comment by dgt41** [comment]
@kricore can you use JLayouts? This way it won't matter what the default behaviour is, as it would be overridable. Check this as an example: https://github.com/joomla/joomla-cms/pull/8508

**Comment by fevangelou** [comment]
Since the modal opens under the component.php subtemplate (?tmpl=component), this is probably some Joomla extension injecting JS and crapping things out, despite our efforts to kill most JS/CSS files injected in that subtemplate

@KannanNaidu To verify this, instead of just clicking the new item link, right-click on it and choose to open it on a new tab. Then check the page for any JS errors logged in the console.

@dgt41 No offence but JLayouts is just another way to make things more complicated in Joomla. If anyone can give me a valid reason to use JLayouts on anything else but an admin/backend layout where it makes sense to re-use key admin interfaces (modals as you mention), I'll quit Joomla and switch to PHPNuke.

It's the reason (along with "traditional" template overrides) why com_content (and other core J extensions) has dozens of override files.

Plus it doesn't really suit the needs of K2 for this purpose.

**Comment by dgt41** [comment]
@fevangelou there are places (e.g.: fields, bootstrap output etc) where using JLayout makes a lot of sense e.g.: https://github.com/joomla/joomla-cms/pull/5871. This way if I use a template based on foundation, with a little more effort, everything should look and work fine and without moo freaking tools. WIN!
Now about the other question: could that be done with plain Html Layouts? Sure! But for some good (or bad) reasons Joomla wants to switch to JLayouts...
