### ISSUE TITLE
Uploading PDF as attachments don't work for some

### ISSUE THREAD

**Issue by M-Falken** [joomlaworks/k2#54]
Hello,

for reference: http://getk2.org/community/New-to-K2-Ask-here-first/182392-New-problem-uploading-pdf-in-Media-Center#183951

There's something strange for some of us, with the upload of PDF files with the media manager.

With the path left blank in the k2 parameters, so default path is in use.
Upload limit is ok (24Mo) and permissions too.
If I try to add a PDF as attachment, the POST sequence is ok, but the result is that there's no file for the attachment of the item in the directory, and obviously no attachment for the item itself.
In the DB table the result is new id created with only the title of the file if we put one.

If we try for example with a jpg, everything is ok.

My php is 5.3.27
Apache 2.2.25

**Comment by kavadas** [comment]
@M-Falken 

There is no error message because the class is not throwing an error. And that's correct, since if you think about it, there is no error. Since all the server side methods for mime detection fail, the class relies on what the browser sends.

As @verot wrote it's the developer's responsibility to provide a descent server setup. 99% percent of the servers out there should work fine with mime detection.
